# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-12 00:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2018, 1, 12, 0, 27, 24, 273328, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
