# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-12 10:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2018, 1, 12, 10, 11, 49, 263164, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
